### ISSUE TITLE
fastfile@0.0.20 seems to have falowing error Note that on snarkjs that uses fastfile@0.0.19 does not have this issue

### ISSUE THREAD

**Issue by constantinpricope2013** [iden3/fastfile#62]
./node_modules/fastfile/src/fastfile.js
Can't import the named export 'O_TRUNC' (imported as 'O_TRUNC') from default-exporting module (only default export is available)

Import trace for requested module:
./node_modules/snarkjs/src/powersoftau_export_challenge.js
./node_modules/snarkjs/src/powersoftau.js
./node_modules/snarkjs/main.js

./node_modules/fastfile/src/fastfile.js
Can't import the named export 'O_CREAT' (imported as 'O_CREAT') from default-exporting module (only default export is available)

Import trace for requested module:
./node_modules/snarkjs/src/powersoftau_export_challenge.js
./node_modules/snarkjs/src/powersoftau.js
./node_modules/snarkjs/main.js

./node_modules/fastfile/src/fastfile.js
Can't import the named export 'O_RDWR' (imported as 'O_RDWR') from default-exporting module (only default export is available)

Import trace for requested module:
./node_modules/snarkjs/src/powersoftau_export_challenge.js
./node_modules/snarkjs/src/powersoftau.js
./node_modules/snarkjs/main.js

./node_modules/fastfile/src/fastfile.js
Can't import the named export 'O_TRUNC' (imported as 'O_TRUNC') from default-exporting module (only default export is available)

Import trace for requested module:
./node_modules/snarkjs/src/powersoftau_export_challenge.js
./node_modules/snarkjs/src/powersoftau.js
./node_modules/snarkjs/main.js

./node_modules/fastfile/src/fastfile.js
Can't import the named export 'O_CREAT' (imported as 'O_CREAT') from default-exporting module (only default export is available)

Import trace for requested module:
./node_modules/snarkjs/src/powersoftau_export_challenge.js
./node_modules/snarkjs/src/powersoftau.js
./node_modules/snarkjs/main.js

**Comment by mehtaphysical** [comment]
I have the same issue. Made a PR with a fix.

**Comment by phated** [comment]
Fixed by https://github.com/iden3/fastfile/commit/2bca53adcf476b9af6c8e8ec08407c48325cc6f3 - I'll get Jordi to make a release.
